// <auto-generated />
namespace StudentsManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddsStudent_migration_After_making_fields_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddsStudent_migration_After_making_fields_required));
        
        string IMigrationMetadata.Id
        {
            get { return "202002210626480_AddsStudent_migration_After_making_fields_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
